# Nama Workflow
name: Deploy to Firebase Hosting on push

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main # Ganti jika nama branch utama Anda bukan 'main' (misal: 'master')

jobs:
  deploy: # Nama job bisa disederhanakan menjadi 'deploy'
    runs-on: ubuntu-latest # Menggunakan server Linux
    steps:
      # Langkah 1: Mengunduh kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Deploy ke Firebase Hosting
      # Langkah build sudah dihilangkan karena tidak diperlukan
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          channelId: live
          projectId: 'trakindomeetingroom'
